Feature/landing page
feedoong/feedoong-frontend pull request #13
Opened 2022-09-30 12:22 UTC by seo337dc

## Motivation 🤔
- 랜딩 페이지 상단 구성
- 랜딩 페이지 메인 부분 구성

<br>

## Key Changes 🔑
<img width="1676" alt="스크린샷 2022-09-30 오후 9 20 29" src="https://user-images.githubusercontent.com/65284962/193268339-79d5875c-bce4-4135-88c7-ad1d042f2d5b.png">
<br>
<img width="1671" alt="스크린샷 2022-09-30 오후 9 20 56" src="https://user-images.githubusercontent.com/65284962/193268429-5f8e8501-2c62-41fa-acb0-97101c7f2c9b.png">

<br>

## To Reviews 🙏🏻

-

2022-09-30 12:23 UTC, seo337dc commented
랜딩 페이지의 파일 및 폴더명을 임시로 Main이라고 지었습니다. 너무 애매한데 다른 파일 명이나 명칭이 있는지 조언이 필요합니다 ㅠㅠ

2022-10-01 15:07 UTC, eunsonny requested changes
스타일 속성들을 조금 변경하면 불필요한 태그들을 줄일 수 있을 것 같아요 🙌🏻 음 그리고 Main 보다는 랜딩페이지니까 Landing으로 하는건 어떨까요 🤔.. 참신한 아이디어는 아니긴한거 같은데 (ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ) 더 참신한 아이디어는 다음 분이 내주실거에요

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.style.tsx
> +  height: 100%;
```suggestion
  height: 400px
  margin: 0 180px;
```
```height: 400px```로 바꾸고 ```margin: 0 180px``` 을 추가하면 Container 와 ContentsWrapper를 사용하지 않아도 똑같은 UI를 구현할 수 있을 것 같아요!

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.style.tsx
> +  align-items: center;
```suggestion
  flex-direction: column;
  justify-content: center;
```
align-items 속성을 제거하고 위의 두 속성을 추가하면 S.BoardWrapper 바로 내부에 한번 더 감싸고 있는 <div>태그가 불필요 할 것 같아요 🥺

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +        <S.ContentsWrapper>
```Main.style.tsx``` 파일을 수정하면 ```<S.container>```  ```<S.ContentsWrapper>```는 없어도 괜찮을 것 같습니다 👀 혹시 이렇게 감싸신 이유가 따로 있으실까요...?

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +              <div>
여기의 ```<div>```도 없앨 수 있을 것 같아요!

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +                  <span>
UI상 문단에 가깝고 block요소로 처리하는게 적합할 것 같아서 span 태그보다 p태그가 적합하지 않을까요? 🤔

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +                  </span>
p 태그로 처리한다면 여기의 span 클로징 태그를 없애고
```suggestion

```

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +                  <span>
```suggestion

```

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Main.tsx
> +                  </span>
```suggestion
                  </p>
```
여기서 p태그를 클로징 해주시면 될 것 같습니당!

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Top/Top.style.tsx
> +`
```suggestion
  ${getTypographyStyles('Headline4_B')};
`
```
여기에 타이포그라피 스타일 속성을 추가해주면 ButtonContentsWrapper와 p태그는 없앨 수 있을 것 같아요 👀

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Top/Top.tsx
> +        <S.ButtonContentsWrapper onClick={() => {}}>
onClick을 GoogleLoginButton 태그로 옮겨주시고 ButtonContentsWrapper는 없어도 좋을 것 같습니다

2022-10-01 15:07 UTC, eunsonny commented on next-app/src/components/views/Main/Top/Top.tsx
> +          <p>크롬에 추가하기</p>
```suggestion
         크롬에 추가하기
```
p태그 없이 그냥 버튼명만 써주면 될 것 같아요!

2022-10-02 20:23 UTC, saengmotmi commented
> 랜딩 페이지의 파일 및 폴더명을 임시로 Main이라고 지었습니다. 너무 애매한데 다른 파일 명이나 명칭이 있는지 조언이 필요합니다 ㅠㅠ

그냥 Landing 같은건 어때요?

2022-10-02 20:24 UTC, saengmotmi approved these changes
은선님 리뷰 내용대로 불필요하게 중첩된 태그들만 정리하면 좋을거 같습니다

2022-10-16 07:03 UTC, seo337dc commented on next-app/src/components/views/Main/Main.style.tsx
> +  height: 100%;
해당 코드로 변경 완료했어요 ㅎㅎㅎ

2022-10-16 07:13 UTC, seo337dc commented on next-app/src/components/views/Main/Main.tsx
> +        <S.ContentsWrapper>
위에 작성하신 스타일로 적용하니 바로바로 되네욤 ㅎㅎㅎㅎ 감사합니다. 
해당 코드로 수정했어요~

2022-10-16 07:13 UTC, seo337dc commented on next-app/src/components/views/Main/Main.tsx
> +              <div>
해당 스타일로 적용하니 바로 되네욤 ㅎㅎㅎ

2022-10-16 07:14 UTC, seo337dc commented on next-app/src/components/views/Main/Main.tsx
> +                  </span>
해당 코드는 나중에 백으로부터 받은 에디터를 html으로 다시 파싱을 할 예정입니다.
이부분은 백과 연결 후 다시 수정할 예정입니다.

2022-10-16 07:16 UTC, seo337dc commented on next-app/src/components/views/Main/Top/Top.style.tsx
> +`
불필요한 코드였네욤 ㅎㅎㅎ

2022-10-16 07:16 UTC, seo337dc commented on next-app/src/components/views/Main/Top/Top.tsx
> +          <p>크롬에 추가하기</p>
수정 완료!!!

2022-10-16 07:17 UTC, seo337dc commented on next-app/src/components/views/Main/Top/Top.tsx
> +        <S.ButtonContentsWrapper onClick={() => {}}>
바로 적용했습니다.,

2022-10-16 07:25 UTC, seo337dc commented
충돌로 인하여 머지 에러...
잠시 브랜치 지운뒤 새로 다시 오픈해보겠습니다,

2022-10-16 07:25 UTC, seo337dc commented
충돌로 인하여 머지 에러...
잠시 브랜치 지운뒤 새로 다시 오픈해보겠습니다,

2022-10-17 01:00 UTC, eunsonny approved these changes
수정하시느라 고생하셨어요!!! 🙌

2022-10-21 16:22 UTC, merged