GNB, LNB,  마이페이지 추가
feedoong/feedoong-frontend pull request #6
Opened 2022-09-02 17:46 UTC by eunsonny

## Motivation 🤔

- GNB 추가
- LNB 추가
- 마이페이지 UI 작업
<br>

## Key Changes 🔑
<img width="1300" alt="스크린샷 2022-09-03 오전 2 32 25" src="https://user-images.githubusercontent.com/67362026/188207922-1248bd64-bf57-41b0-82f9-610ad2478345.png">

- src/common에 Nav, SideNavBar(LNB), TopNavBar(GNB) 컴포넌트 추가
- src/views/MyPage/MyPageView 컴포넌트 추가
- src/views/MyPage/InfoRow 컴포넌트 추가
- src/aseets/icons 추가
<br>

## To Reviews 🙏🏻

- 파일위치나 폴더구조 컨벤션에 잘 맞는지 모르겠네요. 수정이 필요한 부분이 있으면 알려주세요!
- develop rebase는 했는데 컬러나 타이포스타일 세팅은 아직 적용을 못했네요 추후 적용해서 수정하도록 하겠습니다 (...)
- 사이드 바 노출 시에 애니메이션 추가 예정입니다.
- 메인 타이틀 'feedoong' 폰트 변경 예정입니다.

2022-09-02 18:07 UTC, saengmotmi requested changes
수고하셨습니다~ 리뷰 확인해주세요!

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.style.ts
> +  color: #8c8c8c;
gray600 써주시면 될거 같습니다

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.style.ts
> +  font-weight: 600;
타이포그래피는 피그마에서 종류 확인하시고 제가 만들어둔 util 함수 사용해주시면 될거 같슴다
<img width="228" alt="image" src="https://user-images.githubusercontent.com/35240142/188210084-54604b84-59b6-4b7c-8da0-399421660cf0.png">
```tsx
getTypographyStyle("Headline3_B");
```

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.tsx
> +}) => {
```suggestion
import * as S from './MenuItem.style';

interface Props {
  iconUrl: string;
  title: string;
}

export const MenuItem = ({
  iconUrl,
  title,
}: Props) => {
```
props 타입은 이런 형태로 작성해주세요!

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/SideMenuBar.style.ts
> +  background-color: #f5f5f5;
색상이랑 타이포그래피 관련 속성들 전반적으로 확인해서 교체 해주시면 좋을거 같슴다

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/common/TopNavBar/TopNavBar.tsx
> +export const TopNavBar = ({ openSideBar }: any) => {
any 🙅

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/views/MyPage/ InfoRow/InfoRow.tsx
> +}): JSX.Element => {
```suggestion
}) => {
```
리턴 타입 명시해주지 않아도 React.ReactNode로 추론해주지 않을까요?
그리고 JSX.Element과 React.ReactNode는 거의 차이가 없지만 개인적으로는 ReactNode 쪽으로 통일해서 쓰는 편입니다

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/views/MyPage/MyPageView.tsx
> +import { InfoRow } from './ InfoRow/InfoRow'
```suggestion
import { InfoRow } from './InfoRow/InfoRow'
```

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/pages/myPage/index.tsx
> +import { MyPageView } from 'components/views/MyPage/MyPageView'
```suggestion
import { MyPageView } from 'components/views/MyPage'
```
저는 views/MyPage 쪽 폴더 하위 구조를 이렇게 잡았으면 좋겠습니다
```
index.ts
MyPageContainer.tsx
```
```ts
// index.ts
export { default } from "./MyPageViewContainer"
```

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/views/MyPage/MyPageView.style.ts
> +  }
gap을 써주면 first-child를 쓸 필요가 없을거 같습니다
순서 같은 불안정한 값을 기준으로 스타일을 주는 방법은 가급적이면 피하는게 좋을거 같아요

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/views/MyPage/MyPageView.style.ts
> +  color: white;
white 값도 정의된 색상을 써주세요! 나중에 어떤 화이트 색상으로 바뀔지 모르니까요!

2022-09-02 18:07 UTC, saengmotmi commented on next-app/src/components/views/MyPage/ InfoRow/InfoRow.style.ts
> +  }
first-child와 같은 이유로 피했으면 좋겠는데 태그 구조를 보니 div 태그로 한번 감싸고 그 바깥쪽 태그에 margin-bottom: 60px을 주면 어떨까 싶어요

2022-09-03 04:30 UTC, Yeongjae-Shin requested changes

2022-09-03 04:30 UTC, Yeongjae-Shin commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.tsx
> +          <Image src={iconUrl} width="14" height="14" alt="menu_icon" />
아이콘 같은 경우는 `next/image` 의 `priority` 속성을 이용해서 `preload` 시켜주면 더 좋을 것 같습니다!

2022-09-03 04:50 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.tsx
> +          <Image src={iconUrl} width="14" height="14" alt="menu_icon" />
@Yeongjae-Shin 나중에 쭉 훑으면서 거슬리는 친구들 위주로 잡아주는게 어떨까 싶어요 전부 preload 하면 의미가 좀 퇴색되니깐

2022-09-04 09:47 UTC, eunsonny commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.tsx
> +}) => {
넵 interface로 선언해서 사용할게요!

2022-09-04 09:47 UTC, eunsonny commented on next-app/src/components/common/SideNavBar/SideMenuBar.style.ts
> +  background-color: #f5f5f5;
넹 요건 적용하려고 계획했던거라 전반적으로 다 교체하겠습니다

2022-09-04 09:47 UTC, eunsonny commented on next-app/src/components/common/TopNavBar/TopNavBar.tsx
> +export const TopNavBar = ({ openSideBar }: any) => {
오우 이건 실수로 남겨놨네요 수정할게요!

2022-09-04 10:42 UTC, eunsonny commented on next-app/src/components/views/MyPage/MyPageView.style.ts
> +  }
gap을 사용하니까 더 간편하게 해결되네요 👍🏻

2022-09-04 10:49 UTC, eunsonny commented on next-app/src/components/common/SideNavBar/MenuItem/MenuItem.tsx
> +          <Image src={iconUrl} width="14" height="14" alt="menu_icon" />
TopNavBar에 있는 메뉴아이콘은 항시 노출되는 아이콘이라 priority 적용시키고 sideNavBar의 아이콘은 항상 노출되는 아이콘이 아니라 추후에 보고 거슬리면 적용하면 좋을 것 같아서 그렇게 수정해볼게요!

2022-09-04 14:38 UTC, saengmotmi commented on next-app/src/styles/fonts.ts
> +`
https://github.com/feedoong/feedoong-frontend/blob/dev/next-app/src/pages/_document.tsx#L47-L54

저희 폰트 이렇게 추가했어요

2022-09-04 15:07 UTC, eunsonny commented on next-app/src/components/views/MyPage/ InfoRow/InfoRow.tsx
> +}): JSX.Element => {
네 추론이 가능한 값이라 명시할 필요가 없을 것 같아 삭제 했습니다. JSX.Element보다는 ReactNode가 더 넓은 범주의 값이니 굳이 JSX.Element로 제한해야 하는 경우가 아니면 ReacNode로 사용하는게 좋겠네요

2022-09-04 15:16 UTC, eunsonny commented on next-app/src/styles/fonts.ts
> +`
음 넵 이렇게 수정할게요!

2022-09-04 15:27 UTC, saengmotmi approved these changes
수고하셨습니다~

2022-09-04 15:27 UTC, saengmotmi commented on next-app/src/assets/icons/index.ts
> +import BlingBling from './bling_icon.svg'
<img width="691" alt="image" src="https://user-images.githubusercontent.com/35240142/188320962-5da3ca6b-6740-4c54-a838-ba513250b406.png">
Sparkles 어떨까요? ㅎㅎ

2022-09-04 15:27 UTC, saengmotmi commented on next-app/src/components/common/SideNavBar/SideMenuBar.style.ts
> +  z-index: 10;
나중을 위해서 z-index의 레이어를 객체 형태로 관리해줘도 좋을거 같아요 styles/constants.ts 같은 곳에 넣어주면 어떨까요?

2022-09-04 15:27 UTC, saengmotmi commented on next-app/src/components/common/TopNavBar/TopNavBar.style.ts
> +  z-index: 10;
얘도요

2022-09-04 16:57 UTC, eunsonny commented on next-app/src/assets/icons/index.ts
> +import BlingBling from './bling_icon.svg'
네 원하신다면ㅎㅎ

2022-09-04 16:57 UTC, eunsonny commented on next-app/src/components/common/SideNavBar/SideMenuBar.style.ts
> +  z-index: 10;
네 그게 좋을 것 같네요 수정 했습니당

2022-09-24 07:59 UTC, merged