Add/feedoong my page
feedoong/feedoong-frontend pull request #9
Opened 2022-09-13 12:01 UTC by seo337dc

## Motivation 🤔

- 피드 추가 Input & 피드 목록 카드 / 그리드 뷰 선택 기능
- input 입력시 유효성 검사 & 입력된 값 취소 기능

## Key Changes 🔑

| 내가 저장한 게시물 카드 리스트 | 내가 등록한 채널 카드 리스트
|--|--|
<img width="647" alt="스크린샷 2022-09-13 오후 7 49 58" src="https://user-images.githubusercontent.com/65284962/189883260-1d7a2868-4d92-4d3b-b2d2-8c364da2b146.png">|<img width="650" alt="스크린샷 2022-09-13 오후 7 50 12" src="https://user-images.githubusercontent.com/65284962/189883347-1c97ed20-7510-40d9-9e33-89fabe59486f.png">


- 상단 고정 추가

| 내가 저장한 게시물 | 내가 등록한 채널 
|--|--|
<img width="650" alt="스크린샷 2022-09-13 오후 8 56 19" src="https://user-images.githubusercontent.com/65284962/189894854-133228ee-a08f-4a41-a8ae-ec1db655491c.png">|<img width="650=" alt="스크린샷 2022-09-13 오후 8 56 38" src="https://user-images.githubusercontent.com/65284962/189895178-16c35d84-01ba-4840-98fc-e26aef84e48a.png">

-

## To Reviews 🙏🏻

-

2022-09-18 11:46 UTC, eunsonny commented
지금 ```src/components/mypage``` 아래에 ```channel```과 ```post``` 폴더가 있는데, 저희 [README.md](https://github.com/feedoong/feedoong-frontend/tree/dev/next-app#readme)에서 정한 컨벤션대로 ```src/components/view/[page명]``` 밑으로 ```channel```과 ```post```가 들어가야 할 것 같아요. 그리고 별도의 마이페이지가 존재하기 때문에 ```mypage```라는 폴더명 말고 다른 이름을 사용해야 추후에 혼동을 줄일 수 있을 것 같습니다!

2022-09-18 11:58 UTC, eunsonny requested changes

2022-09-18 11:58 UTC, eunsonny commented on next-app/src/components/common/Gird/Grid.style.tsx
> +    color: #8c8c8c;
color중에 grayScale에 있는 건 해당 변수명으로 적용해주시면 좋을 것 같아요!

2022-09-18 11:58 UTC, eunsonny commented on next-app/src/components/common/Layout/index.ts
> +export { default } from './Layout'
Layout 폴더 내부 파일들을 보니 TopNav(GNB) 만들어 놓으신 것 같은데, 이 부분은 제가 할당받아서 이미 만들어 놓은 부분이라 ```pages/_app.tsx``` 파일에 ```Nav``` 컴포넌트로 적용 될 것 같아요! 게시물 상단 고정 때문에 이렇게 만들어 놓으신 것 같은데 다른 방식이 고려되어야 하지 않을까요 🤔 TopNav는 어떤 페이지이던 항상 상단에 고정 노출되기 때문에, 내가 저장한 게시물 페이지나 내가 등록한 채널 페이지에서 Nav의 height 만큼 상단에 여백을 주면 충분히 상단 고정이 가능할 것 같습니다.

2022-09-18 11:58 UTC, eunsonny commented on next-app/src/components/mypage/post/PostContainer.tsx
> +        <S.Title>내가 등록한 채널</S.Title>
PostContainer에 title이 내가 등록한 채널이고, ChannelContainer의 title이 내가 저장한 게시물로 되어 있는데, 이거 서로 바뀐거 같은데... 맞죠(?!?!?)ㅋㅋㅋㅋㅋㅋ 이거 서로 바뀌어야 할 것 같네요

2022-09-18 11:58 UTC, eunsonny commented on next-app/src/components/mypage/post/PostContainer.tsx
> +  const [isCard, setIsCard] = useState(true)
ChannelContainer에서도 그렇고 여기서도 보여지는 아이템 종류(card / grid)를 ```isCard: boolean``` 값으로 컨트롤 하고 있는데 그러면 ```isCard:false```일 경우에는 어떤 아이템으로 보여지고 있는지 명시적이지 않은 것 같아서 boolean 값보다는 ```'card' | 'grid'```와 같이 union 타입으로 관리하면 어떨까요? union 타입이라면 추후에 렌더링 아이템 종류가 추가 된다고 했을 때도 더 관리하기 편할 것 같아요!

2022-09-18 11:58 UTC, eunsonny commented on next-app/src/components/mypage/post/PostContainer.tsx
> +  const handleOption = (value: boolean) => setIsCard(value)
아이템 종류를 유니온 타입으로 관리한다면, handleOption 함수에서도 인자로 boolean 값이 아닌 아이템 종류(optionType)를 받을수 있게 되어 좀 더 명시적이고 가독성 높은 코드를 쓸 수 있을 것 같아요 🥺

2022-09-19 01:35 UTC, Yeongjae-Shin requested changes

2022-09-19 01:35 UTC, Yeongjae-Shin commented on next-app/src/components/common/Gird/Grid.style.tsx
> +  }
이렇게 되면 스타일이 겹쳐지는데 뭐가 맞는건가요? 그리고 경로 오타 있습니다.

`src/components/common/Gird/Grid.style.tsx` => `src/components/common/Grid/Grid.style.tsx`

2022-09-19 01:35 UTC, Yeongjae-Shin commented on next-app/src/components/mypage/post/Grid.style.tsx
> +import styled from 'styled-components'
`common`에 만들어둔 그리드 스타일이랑 똑같은거 아닌가요? 🤔

2022-09-19 01:35 UTC, Yeongjae-Shin commented on next-app/src/components/mypage/post/Grid.tsx
> +const Container = styled.div`
여기도 겹치는 것 같은데 확인 부탁드립니다.

2022-09-21 10:27 UTC, seo337dc commented
> 



> 지금 `src/components/mypage` 아래에 `channel`과 `post` 폴더가 있는데, 저희 [README.md](https://github.com/feedoong/feedoong-frontend/tree/dev/next-app#readme)에서 정한 컨벤션대로 `src/components/view/[page명]` 밑으로 `channel`과 `post`가 들어가야 할 것 같아요. 그리고 별도의 마이페이지가 존재하기 때문에 `mypage`라는 폴더명 말고 다른 이름을 사용해야 추후에 혼동을 줄일 수 있을 것 같습니다!

mypage 안에 `channel`과 `post`를 분리할려고 했었는데요. 그냥 `view안에` `muChannel`과 `myPost`로 따로 나누는게 나을 듯합니다.
수정 후 올리도록 하겠습니다.

2022-09-21 10:31 UTC, seo337dc commented on next-app/src/components/common/Gird/Grid.style.tsx
> +    color: #8c8c8c;
해당 관련된 색들 모두 변경하도록 하겠습니다.

2022-09-21 10:33 UTC, seo337dc commented on next-app/src/components/common/Layout/index.ts
> +export { default } from './Layout'
이 부분은 다시 한번 고민하도록 해보겠습니다.
우선 은선님께서 개발하신 GNB를 보고 다시 생각해보도록 하겠습니다.

2022-09-21 10:49 UTC, seo337dc commented on next-app/src/components/mypage/post/Grid.style.tsx
> +import styled from 'styled-components'
Post에서 사용하는 카드와 거의 일치하는데, 약간에 일부분이 다른경우가 있습니다. 이부분에 대해서 종택님이랑 얘기를 드렸고,
임시로 Post에 따로 Card를 가지고 있다가. 추후 합치던 변경하던 할 예정입니다.

2022-09-21 11:13 UTC, seo337dc commented on next-app/src/components/mypage/post/Grid.tsx
> +const Container = styled.div`
Channel과 Feed는 common에 있는 Grid를 사용하면 되지만,  Post 같은 경우 달라서 일단 common으로 사용하기 힘듭니다.
common 내부의 Grid랑 Card를 수정하거나 추가할려고 했으나, 명칭이나 이런 부분들이 애매하여 일단 분리를 하고 다시 common에 합치던 할려고 합니다.

2022-09-21 11:24 UTC, seo337dc commented on next-app/src/components/mypage/post/PostContainer.tsx
> +        <S.Title>내가 등록한 채널</S.Title>
100% 착각하고 작성하지 않았을까합니다 ㅎㅎㅎ

2022-09-21 11:25 UTC, seo337dc commented on next-app/src/components/mypage/post/PostContainer.tsx
> +  const [isCard, setIsCard] = useState(true)
좋은 의견인거 같습니다. 수정하도록 하겠습니다.

2022-09-21 11:27 UTC, seo337dc commented
> > 
> 
> > 지금 `src/components/mypage` 아래에 `channel`과 `post` 폴더가 있는데, 저희 [README.md](https://github.com/feedoong/feedoong-frontend/tree/dev/next-app#readme)에서 정한 컨벤션대로 `src/components/view/[page명]` 밑으로 `channel`과 `post`가 들어가야 할 것 같아요. 그리고 별도의 마이페이지가 존재하기 때문에 `mypage`라는 폴더명 말고 다른 이름을 사용해야 추후에 혼동을 줄일 수 있을 것 같습니다!
> 
> 말씀하신데로, `channel`, `post`컴포넌트들은 모두 view폴더안으로 이동하였고, mypage 폴더는 제거하였습니다.

2022-09-21 11:53 UTC, seo337dc commented on next-app/src/components/mypage/post/Grid.style.tsx
> +import styled from 'styled-components'
common > Card.style에서 Post에 필요한 스타일을 따로 추가하였습니다. 단 Post에서는 아직 Post용 Card컴포넌트는 존재합니다.

2022-09-21 12:21 UTC, seo337dc reviewed
@Yeongjae-Shin [이전 리뷰](https://github.com/feedoong/feedoong-frontend/pull/9#discussion_r973814239)

- 일단 common에 있는 Card스타일으로 적용하고, Post에 필요한 스타일을 추가했습니다.
아직 Post랑 common의 Card스타일이 맞지 않는 부분이 있어서, Post의 Card컴포넌트는  냅뒀습니다.

2022-09-21 12:22 UTC, seo337dc reviewed
@Yeongjae-Shin  [이전 리뷰](https://github.com/feedoong/feedoong-frontend/pull/9#discussion_r973813323)
- Grid또한 common의 Grid.style에 적용했고, 필요한 부분은 따로 추가했습니다.

2022-09-21 12:24 UTC, seo337dc reviewed
@eunsonny [이전 리뷰](https://github.com/feedoong/feedoong-frontend/pull/9#discussion_r973708794)

- 말씀하신대로, union으로 'card | grid'로 구분하도록 변경했습니다.

2022-09-24 09:10 UTC, merged